=== tsnyder-gs1us/GS1DigitalLicenses/schemas/prefix.json
{
  "$id": "GS1-Prefix-License-Schema",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "1.0.0",
  "title": "GS1PrefixLicenseCredential",
  "description": "A GS1 Prefix is issued by GS1 Global Office and allocated a GS1 Member Organization or to itself for the purpose of issuing GS1 Company Prefix, GS1 identification key, delegated GS1 Prefix, or delegated GS1 identification key licenses.",
  "type": "object",
  "$defs": {
    "GS1DigitalLink": {
      "title": "GS1 Digital Link",
      "type": "string",
      "format": "uri",
      "pattern": "^https?:(\\/\\/((([^\\/?#]*)@)?([^\\/?#:]*)(:([^\\/?#]*))?))?([^?#]*)(((\\/(01|8006|8013|8010|414|417|8017|8018|255|00|253|401|402|8003|8004)\\/)(\\d{4}[^\\/]+)(\\/[^/]+\\/[^/]+)?\\/?(\\?([^?\\n]*))?(#([^\\n]*))?))$"
    },
    "DID": {
      "title": "Decentralized Identifier (DID)",
      "type": "string",
      "format": "uri",
      "pattern": "^did:[a-z0-9]+:(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+(?::(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+)*$"
    },
    "Issuer": {
      "title": "Issuer",
      "description": "The issuer of the credential",
      "type": "object",
      "properties": {
        "id": {
          "title": "Issuer Identifier",
          "type": "string",
          "format": "uri"
        },
        "name": {
          "title": "Issuer Name",
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "RenderMethod": {
      "type": "object",
      "description": "Rendering support",
      "properties": {
        "id": {
          "title": "Render Method Id",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string",
          "const": "SvgRenderingTemplate"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "type"
      ]
    },
    "CredentialSchema": {
      "type": "object",
      "properties": {
        "id": {
          "title": "Credential Schema Identifier",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "title": "Credential Schema Type",
          "const": "JsonSchema"
        }
      },
      "required": [
        "id",
        "type"
      ]
    },
    "CredentialStatus": {
      "type": "object",
      "description": "Revocation supported.",
      "properties": {
        "id": {
          "title": "Credential Status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string",
          "const": "BitstringStatusListEntry"
        },
        "statusPurpose": {
          "type": "string",
          "const": "revocation"
        },
        "statusListIndex": {
          "type": "string"
        },
        "statusSize": {
          "type": "number"
        },
        "statusListCredential": {
          "type": "string",
          "format": "uri"
        },
        "statusMessage": {
          "type": "array",
          "readOnly": true,
          "items": {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "enum": [
                  "0x0",
                  "0x1"
                ]
              },
              "message": {
                "type": "string",
                "enum": [
                  "valid",
                  "revoked"
                ]
              }
            },
            "required": [
              "status",
              "message"
            ]
          }
        }
      },
      "required": [
        "id",
        "type",
        "statusPurpose",
        "statusListIndex",
        "statusListCredential"
      ]
    },
    "Organization": {
      "title": "An Organization is any legal or physical entity involved at any point in any supply chain and upon which there is a need to retrieve predefined information. An Organization is uniquely identified by a Global Location Number (GLN).",
      "type": "object",
      "properties": {
        "gs1:partyGLN": {
          "title": "13-digit GLN that is being used to identify a legal entity or function. If gs1:glnType is present, gs1:partyGLN SHALL only be used when gs1:GLN_TypeCode includes LEGAL_ENTITY and/or FUNCTION",
          "type": "string",
          "pattern": "^\\d{13}$"
        },
        "gs1:organizationName": {
          "title": "The name of the organization expressed in text.",
          "type": "string"
        }
      },
      "required": [
        "gs1:partyGLN",
        "gs1:organizationName"
      ]
    },
    "ValidFrom": {
      "description": "Date from which the credential is to be considered valid.",
      "type": "string",
      "format": "date-time"
    }
  },
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      },
      "allOf": [
        {
          "contains": {
            "const": "https://www.w3.org/ns/credentials/v2"
          }
        },
        {
          "contains": {
            "const": "https://ref.gs1.org/gs1/vc/license-context"
          }
        }
      ]
    },
    "id": {
      "type": "string",
      "format": "uri"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "allOf": [
        {
          "contains": {
            "const": "VerifiableCredential"
          }
        },
        {
          "contains": {
            "const": "GS1PrefixLicenseCredential"
          }
        }
      ]
    },
    "issuer": {
      "$ref": "#/$defs/Issuer"
    },
    "validFrom": {
      "$ref": "#/$defs/ValidFrom"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "credentialSubject": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/DID"
        },
        "organization": {
          "$ref": "#/$defs/Organization"
        },
        "licenseValue": {
          "type": "string",
          "title": "GS1 Prefix License Value",
          "pattern": "^\\d{2,7}$"
        },
        "alternativeLicenseValue": {
          "title": "GS1 Prefix Alternative License Value. This field is optional.",
          "type": "string"
        }
      },
      "required": [
        "id",
        "licenseValue",
        "organization"
      ]
    },
    "credentialSchema": {
      "oneOf": [
        {
          "$ref": "#/$defs/CredentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CredentialSchema"
          },
          "minItems": 1
        }
      ]
    },
    "credentialStatus": {
      "oneOf": [
        {
          "$ref": "#/$defs/CredentialStatus"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CredentialStatus"
          },
          "minItems": 1
        }
      ]
    },
    "renderMethod": {
      "oneOf": [
        {
          "$ref": "#/$defs/RenderMethod"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RenderMethod"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "validFrom",
    "name",
    "description",
    "credentialSubject",
    "credentialStatus",
    "credentialSchema",
    "renderMethod"
  ]
}

=== tsnyder-gs1us/GS1DigitalLicenses/samples/gcp-sample.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://ref.gs1.org/gs1/vc/license-context"
  ],
  "id": "https://cbpvsvip-vc-api.gs1us.org/credentials/081015955",
  "type": [
    "VerifiableCredential",
    "GS1CompanyPrefixLicenseCredential"
  ],
  "issuer": {
    "id": "did:web:cbpvsvip-vc.gs1us.org",
    "name": "GS1 US"
  },
  "name": "GS1 Company Prefix License",
  "description": "THIS GS1 DIGITAL LICENSE CREDENTIAL IS FOR TESTING PURPOSES ONLY. A GS1 Company Prefix License is issued by a GS1 Member Organization or GS1 Global Office and allocated to a user company or to itself for the purpose of generating tier 1 GS1 ID Keys.",
  "validFrom": "2024-01-25T12:30:00.000Z",
  "credentialSubject": {
    "id": "did:web:healthytots.net",
    "organization": {
      "gs1:partyGLN": "0810159550000",
      "gs1:organizationName": "Healthy Tots"
    },
    "extendsCredential": "https://id.gs1.org/vc/license/gs1_prefix/08",
    "licenseValue": "081015955",
    "alternativeLicenseValue": "81015955"
  },
  "credentialSchema": {
    "id": "https://id.gs1.org/vc/schema/v1/companyprefix",
    "type": "JsonSchema"
  },
  "credentialStatus": {
    "id": "https://cbpvsvip-vc-api.gs1us.org/status/801c6cc6-4fc4-4aa3-a347-3b31a175ac14#10010",
    "type": "BitstringStatusListEntry",
    "statusPurpose": "revocation",
    "statusListIndex": "10010",
    "statusListCredential": "https://cbpvsvip-vc-api.gs1us.org/status/801c6cc6-4fc4-4aa3-a347-3b31a175ac14/"
  },
  "renderMethod": [
    {
      "id": "https://woodycreek.github.io/GS1DigitalLicenses/templates/gs1-sample-license-template.svg",
      "type": "SvgRenderingTemplate",
      "name": "Web Display",
      "css3MediaQuery": "@media (min-aspect-ratio: 3/1)"
    }
  ]
}
